bracketSpacing: true
printWidth: 110
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
endOfLine: lf

overrides:
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
